list_for_tasks = [1, 2, 5, 8, 9, 6, 3, 11, 10, -8, -6, -3]

# PRIMARY LEVEL

# Task 1

print(f'Сума чисел списку: {sum(list_for_tasks)}')

# Task 2

print(f'Мінімальне число списку: {min(list_for_tasks)}')

# Task 3

list_for_tasks.reverse()
print(f'Перевернутий список: {list_for_tasks}')

# Task 4

list_for_task_4 =[]

for i in range(len(list_for_tasks)):
    if list_for_tasks[i] % 2 != 0:
        list_for_task_4.append(list_for_tasks[i])

print(f'Непарні числа зі списку: {list_for_task_4}')

# Task 5

x = int(input("Введіть число на яке будемо множити список: "))
list_for_task_5 = []

for i in range(len(list_for_tasks)):
    list_for_task_5.append(list_for_tasks[i] * x)

print(f'Елементами з існуючого списку помножені на {x}: {list_for_task_5}')

# EASY LEVEL

# Task 1

x_2 = int(input("Введіть число більше якого мають бути елементи списку: "))
list_for_task_6 = []

for i in range(len(list_for_tasks)):
    if list_for_tasks[i] > x_2:
        list_for_task_6.append(list_for_tasks[i])

print(f'Елементи списку більші за {x_2}: {list_for_task_6}')

# Task 2

list_for_task_7 = []

for i in range(len(list_for_tasks)):
    if list_for_tasks[i] > 0:
        list_for_task_7.append(list_for_tasks[i])
        average = sum(list_for_task_7)/len(list_for_task_7)

print(f'Середнє значення додатних значень списку: {average}')

# Task 3

list_for_task_8 = []

for i in list_for_tasks:
    if i not in list_for_task_8 and i != x_2:
        list_for_task_8.append(i)

print(f'Максимальне значення у списку: {max(list_for_task_8)}')

# Task 4

y = int(input("Введіть число, яким будемо перевіряти елементи списку: "))
list_for_task_9 = []

for i in list_for_tasks:
    if i in list_for_tasks and i % y == 0:
        list_for_task_9.append(i)

print(f'Сума чисел, які діляться на {y}: {sum(list_for_task_9)}')

# Task 5

list_for_task_10 = []

for i in list_for_tasks:
    list_for_task_10.append(i ** 2)

print(f'Список квадратів елементів існуючого списка: {list_for_task_10}')

# Task 6

list_for_task_11 = []

for i in list_for_tasks:
    if i > 0:
        list_for_task_11.append(i)

print(f'Додатні числа зі списку: {list_for_task_11}')

# Task 7

prefics = input("Введіть префікс, за допомогою якого будемо перевіряти слова (such as un, re, pre, mis, dis, over, under): ")
list_of_words = ["unhappy", "unfair", "unlock", "redo", "rewrite", "level", "hello", "world", "madam", "python", "noon", "replay", "preview", "predict", "preheat", "misplace", "mislead", "disconnect", "disagree", "dislike", "overthink", "overwork", "oversleep", "understand", "underrate"] #this list was generated by chat gpt
same_prefics = []

for i in list_of_words:
    if prefics in i:
        same_prefics.append(i)

print(f'Слова з префіксом {prefics}: {same_prefics}')

# Task 8

n = int(input("Cкільки перших чисел списку ви хочете сумувати: "))
list_for_task_13 = []

for i in range(len(list_for_tasks)):
    if i <= (n - 1):
        list_for_task_13.append(list_for_tasks[i])

print(f'Сума перших {n} елементів списку: {sum(list_for_task_13)}')

# Task 9

list_for_task_14 = []

for i in list_of_words:
    if i == i[:: -1]:
        list_for_task_14.append(i)

print(f'Списки всіх паліндромів: {list_for_task_14}')

# Task 10

div = int(input("Введіть число на яке будемо ділити: "))
list_for_task_15 = []

for i in list_for_tasks:
    if i % div == 0:
        list_for_task_15.append(True)
    else:
        list_for_task_15.append(False)

print(f'Елементи списку, які діляться на {div}: {list_for_task_15}')

# MEDIUM LEVEL

# Task 1

x_16 = int(input("Введіть число, на яке має ділитися елемент: "))
y_16 = int(input("Введіть числ, на яке не має ділитися елемент: "))
list_for_task_16 = []

for i in list_for_tasks:
    if i % x == 0 and i % y != 0:
        list_for_task_16.append(i)

print(f'Елементи списку, які діляться на {x_16} і не діляться на {y_16}: {list_for_task_16}')

# Task 2

nested_list = [[1, 2, 8], [4, 7, 3], [], [9, 0], [-1, 90, 5, -11]]
list_for_task_17 = []

for i in nested_list:
    for it in i:
        list_for_task_17.append(it)

print(f'Зведення списку {nested_list} в єдиний список: {list_for_task_17}')

# Task 3

# Список згенерований за допомогою chat gpt

list_with_phrases = ["GoBigOrGoHome", "noWorriesMate", "STaYStrong", "KeepItUP", "simpletest", "HELLOworld"]
list_with_uc = []

for i in list_with_phrases:
    tstring = ""
    for letter in i:
        if letter.isupper() == True:
            tstring += letter
            list_with_uc.append(tstring)

print(f'Окремий список зі списку {list_with_phrases} з великими літерами в підрядках: {list_with_uc}')

# Task 4

list_for_tasks.sort()
print(f'Відсортований список: {list_for_tasks}')

# Task 5

# в цьому завданні було б дууууже корисно, якби нам дали чітку умову, відповідно до якої ми маємо написати код. Але через те, що цього не сталося - мені довелось напрягти chat gpt. 
# Умова від cgat gpt: Якщо число парне — використай його зі списку чисел. Якщо непарне — замість нього встав слово з другого списку (на тій самій позиції).

list_for_task_20 = []

for i in range(len(list_for_tasks)):
    if list_for_tasks[i] % 2 == 0:
        list_for_task_20.append(list_for_tasks[i])
    else:
        list_for_task_20.append(list_of_words[i])

print(f'Список відповідно до умов: {list_for_task_20}')

# Task 6

# Для того, щоб зрозуміти, що таке агрегація словника - використовувала chat gpt. Словний нижче згенерований за допомогою нього.

dict_sales = [
    {"store": "A", "revenue": 200},
    {"store": "B", "revenue": 150},
    {"store": "A", "revenue": 100},
    {"store": "C", "revenue": 250},
    {"store": "B", "revenue": 200}
]
dict_results = {}

for i in dict_sales:
    if i["store"] in dict_results:
        dict_results[i["store"]] += i["revenue"]  
    else:
        dict_results[i["store"]] = i["revenue"]  

print(f'Словник із сумою значень за ключем: {dict_results}')

# Task 7

# Знову було б круто, якби було чітка умова, але через те, що її немає - я попросила chat gpt її придумати.
# Умова від chat gpt: Якщо число менше нуля — заміни його на 0. Всі інші числа залиш без змін.

list_for_task_22 = []

for i in list_for_tasks:
    if i >= 0:
        list_for_task_22.append(i)
    else:
        list_for_task_22.append(0)

print(f'Заміна мінусового числа на нуль: {list_for_task_22}')

# Task 8

x_23 = int(input("Введіть бажану довжину рядка: "))
list_for_task_23 = []

for i in range(len(list_of_words)):
    if len(list_of_words[i]) > x_23:
        list_for_task_23.append(list_of_words[i])

print(f'В списку знайдено {len(list_for_task_23)} елементів з довжиною більше за {x_23}')

# Task 9

# Списки для цього завдання створені за допомогою chat gpt.

emotions = ["happy", "sad", "excited", "angry"]
emojis = ["😊", "😢", "🤩", "😡"]
list_for_task_24 = []

for i in range(len(emotions)):
    list_for_task_24.append(emotions[i])
    list_for_task_24.append(emojis[i])

print(f'Список складений з {emotions} та {emojis}: {list_for_task_24}')

# Task 10

x_25 = int(input("Число в списку має бути більше за: "))
y_25 = int(input("Якщо число менше, множимо його на: "))
list_for_task_25 = []

for i in list_for_tasks:
    if i > x_25:
        list_for_task_25.append(i * y_25)

print(f'Елементи, які більше за {x_25}, помножені на {y_25}: {list_for_task_25}')